### PR TITLE
Remove enforcement of Pipfile. 

### PR DESCRIPTION
**Pull request by zahodi**
- disabled enforcement of Pipfile
update to python3 for Ansible2.8 since python2 is EOL within 3 months.

### CODE REVIEW

**Comment by senorsmile** [comment]
This proposal seems like a good idea.  However, one of the things that isn't addressed here is how to automatically provide for multiple versions of ansible by only specifying an ENV VAR.  This PR breaks that without proposing a solution.

**Comment by zahodi** [comment]
It's not clear how this change breaks the option to automatically provide multilple version when the functionally to do that is not currently in place.

**Comment by senorsmile** [comment]
That functionality is found here: https://github.com/senorsmile/ansible-runner-scripts2/blob/master/run_ansible.sh#L14

That defaults to 2.8, but allows 2.6 and 2.7 as well.

**Comment by zahodi** [comment]
A user still have the option of passing `ANSIBLEVER` to the job, that does not change. It's not clear to me how removal for the Pipfile enforcement prevents users from using different versions.

**Comment by senorsmile** [comment]
Closing this as we resolved the core issue in a different manner.

**Pull request closed without merging**
